### PR TITLE
allow toFrame() out of buffer and configurable pagesize

### PR DESCRIPTION
**Pull request by lukemurray**
This lets someone configure the pageSize for buffering, leaving the default to 5.

Also if `toFrame()` is called with a frame out of buffer it will fetch a new buffer and jump to that location.

### CODE REVIEW

**Comment by lukemurray** [comment]
Don't merge this yet. I relaise it is broken. Working on fixing it now.

**Comment by lukemurray** [comment]
OK this should be good to go. It
- allows a custom page size
- better handles if frames are not continuous
- allows you jump frames even is to a non-buffered frame
- exposes a nice way to get the total frames

**Comment by lukemurray** [comment]
I have also added
- a promise on `toFrame` so a caller knows when the frame has been loaded
- `toFrame` actually requests a few frames back creating a small buffer if they wish to go back a little after jumping to a spot. the promise resolved on the requested frames `onload`

**Comment by lukemurray** [comment]
Also exposes `.fitCanvas()` to manually trigger a resize to the parent container. I found I needed to do this after dynamically loading images to show.

Let me know if you want this PR split up.

**Comment by nterms** [comment]
Thanks for the enhancements. I'll do a new release with this.

**Pull request merged**
